# With infos from
# http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
# https://packaging.python.org/en/latest/appveyor/
# https://github.com/rmcgibbo/python-appveyor-conda-example

# Backslashes in quotes need to be escaped: \ -> "\\"

environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"
    # Workaround for https://github.com/conda/conda-build/issues/636
    PYTHONIOENCODING: "UTF-8"

  matrix:
    # for testing purpose: numpy 1.8 on py2.7, for the rest use 1.10/latest
    # theoretically the CONDA_INSTALL_LOCN could be only two: one for 32bit, one for 64bit
    # but using one for the right python version is hopefully making it fast due to package caching.
    - TARGET_ARCH: "x64"
      CONDA_PY: "27"
      CONDA_NPY: "18"
      PYTHON_VERSION: "2.7"
      TEST_ALL_IMAGES: "no"
      CONDA_INSTALL_LOCN: "C:\\Miniconda-x64"


# We always use a 64-bit machine, but can build x86 distributions
# with the PYTHON_ARCH variable (which is used by CMD_IN_ENV).
platform:
    - x64

# all our python builds have to happen in tests_script...
build: false

init:
  - cmd: "ECHO %PYTHON_VERSION% %CONDA_INSTALL_LOCN%"

install:
  - cmd: set PATH=%CONDA_INSTALL_LOCN%;%CONDA_INSTALL_LOCN%\scripts;%PATH%;
  - cmd: set PYTHONUNBUFFERED=1
  # for obvci_appveyor_python_build_env.cmd
  - cmd: conda install -c pelson/channel/development --yes --quiet obvious-ci
  # for msinttypes and newer stuff
  - cmd: conda config --add channels conda-forge
  - cmd: conda config --set show_channel_urls yes
  - cmd: conda config --set always_yes true
  # For building conda packages
  - cmd: conda install --yes conda-build jinja2 anaconda-client
  # this is now the downloaded conda...
  - conda info -a

  # Fix the appveyor build environment to work with conda build
  # workaround for missing vcvars64.bat in py34 64bit
  - cmd: copy ci\appveyor\vcvars64.bat "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64"
  # workaround for conda build on py27 prefering the normal installed
  # VS tools instead of the also installed Py27 VS compiler (which wouldn't need this workarounds...)
  - cmd: copy "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"

  # For building, use a new environment which only includes the requirements for mpl
  # same things as the requirements in ci/conda_recipe/meta.yaml
  # if conda-forge gets a new pyqt, it might be nice to install it as well to have more backends
  # https://github.com/conda-forge/conda-forge.github.io/issues/157#issuecomment-223536381
  - cmd: conda create -q -n test-environment python=%PYTHON_VERSION% pip setuptools numpy  python-dateutil freetype=2.6 msinttypes "tk=8.5" pyparsing pytz tornado "libpng>=1.6.21,<1.7" "zlib=1.2" "cycler>=0.10" nose mock
  - activate test-environment
  - cmd: echo %PYTHON_VERSION% %TARGET_ARCH%
  - cmd: IF %PYTHON_VERSION% == 2.7 conda install -q functools32

  # Let the install prefer the static builds of the libs
  - set LIBRARY_LIB=%CONDA_PREFIX%\Library\lib
  - cmd: 'mkdir lib || cmd /c "exit /b 0"'
  - copy /Y %LIBRARY_LIB%\zlibstatic.lib lib\z.lib
  - copy /Y %LIBRARY_LIB%\libpng_static.lib lib\png.lib
  # These z.lib / png.lib are not static versions but files which end up as
  # dependencies to the dll file. This is fine for the conda build, but not here
  # and for the wheels
  - del %LIBRARY_LIB%\png.lib
  - del %LIBRARY_LIB%\z.lib
  - set MPLBASEDIRLIST=%CONDA_PREFIX%\Library\;.
  # enables the local freetype build
  - copy ci\travis\setup.cfg .
  # Show the installed packages + versions
  - conda list

test_script:
  # Now build the thing..
  - '%CMD_IN_ENV% python setup.py develop'
  # these should show no z, png, or freetype dll...
  - set "DUMPBIN=%VS140COMNTOOLS%\..\..\VC\bin\dumpbin.exe"
  #- cmd: '"%DUMPBIN%" /DEPENDENTS lib\matplotlib\_png*.pyd'
  #- cmd: '"%DUMPBIN%" /DEPENDENTS lib\matplotlib\ft2font*.pyd'
  - cmd: '"%DUMPBIN%" /DEPENDENTS lib\matplotlib\ft2font*.pyd | findstr freetype.*.dll && exit  /b 1 || exit /b 0'
  - cmd: '"%DUMPBIN%" /DEPENDENTS lib\\matplotlib\\_png*.pyd | findstr z.*.dll && exit /b 1 || exit /b 0'
  - cmd: '"%DUMPBIN%" /DEPENDENTS lib\\matplotlib\\_png*.pyd | findstr png.*.dll && exit /b 1 || exit /b 0'

  # this are optional dependencies so that we don't skip so many tests...
  - cmd: conda install -q pillow miktex
  # autoinstall latex packages (0=no, 1=autoinstall, 2=ask)
  # this adds this to the registry!
  - cmd: initexmf --set-config-value "[MPM]AutoInstall=1"
  # we need to put the real exe files into PATH as subprocess can't call bat files
  # this works for the "old" version of the miktex package, then next version should
  # not need it
  - set "PATH=%PATH%;%CONDA_PREFIX%\Library\miktex\miktex\bin"
  # missing packages on conda-forge for ffmpeg avconv mencoder imagemagick inkscape
  - cmd: conda install -q -c menpo ffmpeg # a repackaged version
  # This install sometimes failed randomly :-(
  #- cmd: choco install imagemagick
  # only install inkscape during one test run as it increases the runtime of one
  # test run from 13 min -> 30 min
  - cmd: if x%TEST_ALL_IMAGES% == xyes; choco install inkscape
  - cmd: if x%TEST_ALL_IMAGES% == xyes; set "PATH=%PATH%;C:\Program Files\Inkscape\inkscape.com"
  # Test import of tkagg backend
  - python -c "import matplotlib as m; m.use('tkagg'); import matplotlib.pyplot as plt; print(plt.get_backend())"
  # tests
  - python tests.py
  # Generate a html for visual tests
  - python visual_tests.py

after_test:
  # After the tests were a success, build packages (wheels and conda)

  # Build the wheel with the static libs
  # Hide the output, the copied files really clutter the build log...
  - cmd: '%CMD_IN_ENV% python setup.py bdist_wheel > NUL:'

  # And now the conda build after a cleanup...
  # cleanup build files so that they don't pollute the conda build but keep the wheel in dist...
  - cmd: git clean -d -x -f -e dist/
  # cleanup the environment so that the test-environment does not leak into the conda build...
  - cmd: set MPLBASEDIRLIST=
  - cmd: set LIBRARY_LIB=
  - cmd: deactivate
  - cmd: path
  - cmd: where python
  - cmd: '%CMD_IN_ENV% conda config --get channels'
  - cmd: '%CMD_IN_ENV% conda build -q .\ci\conda_recipe'

  # Move the conda package into the dist directory, to register it
  # as an "artifact" for Appveyor.
  - cmd: 'copy /Y %CONDA_INSTALL_LOCN%\conda-bld\win-32\*.bz2 dist || cmd /c "exit /b 0"'
  - cmd: 'copy /Y %CONDA_INSTALL_LOCN%\conda-bld\win-64\*.bz2 dist || cmd /c "exit /b 0"'
  - cmd: dir dist\
  - cmd: echo finished...

artifacts:
  - path: dist\*
    name: packages

  - path: bld.bat
    name: buildbat
